### ISSUE TITLE
"Error: No crypto" when requiring forge.bundle.js

### ISSUE THREAD

**Issue by FelixMcFelix** [digitalbazaar/forge#328]
I seem to be having difficulty including the require.js compiled version of forge. As part of a module designed to run server- and client-side, I realised quite quickly that your module was incompatible with webpack. I tried to remedy this by following the instructions in #198 and including the module by:
```javascript
pki = require("../lib/forge.bundle.js").pki
```
This works just fine for compiling with webpack, but trying to run the code on node returns the following stack trace when trying to test with mocha:
```bash
throw new Error('No ' + name);
            ^

Error: No crypto
    at callDep (F:\Dropbox\Public\lv4-proj\repos\conductor-chord\lib\forge.bundl
e.js:185:19)
    at req (F:\Dropbox\Public\lv4-proj\repos\conductor-chord\lib\forge.bundle.js
:346:20)
    at Array.initModule (F:\Dropbox\Public\lv4-proj\repos\conductor-chord\lib\fo
rge.bundle.js:10169:12)
    at Array.module.exports (F:\Dropbox\Public\lv4-proj\repos\conductor-chord\li
b\forge.bundle.js:10395:14)
    at Array.module.exports (F:\Dropbox\Public\lv4-proj\repos\conductor-chord\li
b\forge.bundle.js:16230:14)
    at Array.module.exports (F:\Dropbox\Public\lv4-proj\repos\conductor-chord\li
b\forge.bundle.js:21660:14)
    at Array.module.exports (F:\Dropbox\Public\lv4-proj\repos\conductor-chord\li
b\forge.bundle.js:25981:14)
    at Array.module.exports (F:\Dropbox\Public\lv4-proj\repos\conductor-chord\li
b\forge.bundle.js:26329:14)
    at Object.module.exports (F:\Dropbox\Public\lv4-proj\repos\conductor-chord\l
ib\forge.bundle.js:29496:14)
    at defineFunc (F:\Dropbox\Public\lv4-proj\repos\conductor-chord\lib\forge.bu
ndle.js:29502:10)
    at F:\Dropbox\Public\lv4-proj\repos\conductor-chord\lib\forge.bundle.js:2954
5:14
    at main (F:\Dropbox\Public\lv4-proj\repos\conductor-chord\lib\forge.bundle.j
s:315:39)
    at callDep (F:\Dropbox\Public\lv4-proj\repos\conductor-chord\lib\forge.bundl
e.js:181:18)
    at req (F:\Dropbox\Public\lv4-proj\repos\conductor-chord\lib\forge.bundle.js
:346:20)
    at F:\Dropbox\Public\lv4-proj\repos\conductor-chord\lib\forge.bundle.js:2955
0:8
    at defined (F:\Dropbox\Public\lv4-proj\repos\conductor-chord\lib\forge.bundl
e.js:5:18)
    at Object.<anonymous> (F:\Dropbox\Public\lv4-proj\repos\conductor-chord\lib\
forge.bundle.js:7:3)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (F:\Dropbox\Public\lv4-proj\repos\conductor-chord\src\
Chord.js:15:8)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (F:\Dropbox\Public\lv4-proj\repos\conductor-chord\test
\Chord.js:2:10)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at C:\Users\Kyle\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Users\Kyle\AppData\Roaming\npm\node_modules\mocha\lib
\mocha.js:213:14)
    at Mocha.run (C:\Users\Kyle\AppData\Roaming\npm\node_modules\mocha\lib\mocha
.js:453:10)
    at Object.<anonymous> (C:\Users\Kyle\AppData\Roaming\npm\node_modules\mocha\
bin\_mocha:393:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

I attempted to get around this issue by including a conditional check to choose which version of the module to load based on where the code was being run (in node or the browser) - but this only caused webpack to return the same error as it included the broken variant regardless.

This was my attempt:
```javascript
let pki;
if(typeof module !== 'undefined' && this.module !== module){
	//We're on node!
	console.log("n")
	pki = require("node-forge").pki
} else {
	//We're a browser.
	console.log("b")
	pki = require("../lib/forge.bundle.js").pki
}
```

Unfortunately, I'm at a loss on how to continue from here. Has anyone else run into this issue?

**Comment by drudkiewicz** [comment]
I'm exeriencing the same issue

**Comment by nginnever** [comment]
Also ran into the same problem trying to use webpack with node-forge. My solution currently is to <a href ="http://webpack.github.io/docs/configuration.html#module-noparse">noParse</a> the module and force the bundle in. 

<a href="https://github.com/christianalfoni/react-webpack-cookbook/wiki/Optimizing-development">Example noParse</a>

For my use case I did

Pass a deps path to the forge bundle to the deps functions below
```
var deps = [
    'peer-id/deps/forge.bundle.js'
  ]
```
create the noParse in webpack config that will take the deps
```
module: {
        loaders: [
          { test: /\.json$/, loader: 'json' }
        ],
        noParse: []
      },
```

Feed the deps to the noParse
```
deps.forEach(function (dep) {
    var depPath = path.resolve(node_modules_dir, dep)
    config.webpack.resolve.alias[dep.split(path.sep)[0]] = depPath
    config.webpack.module.noParse.push(depPath)
  })
```

**Comment by nginnever** [comment]
There is work being done "<a href="https://github.com/digitalbazaar/forge/pull/357">see here</a>" for commonJS in forge which will allow tools like webpack to work.

Until then you can use this <a href="https://gist.github.com/nginnever/bd33e0fb49fbcba88d1b">work around</a> for your webpack projects. 

When testing with Karma I had to set forge = forge.forge() for the bundle to work. Not sure why that is atm just a heads up if you start seeing the forge.someFunction is undefined.

**Comment by FelixMcFelix** [comment]
That's good to hear. My current set-up is quite similar, but seems to require manual override in applications which require my module. I'll try this modification out - closing the issue for now.
