### ISSUE TITLE
Problem with extract or package a pfx file

### ISSUE THREAD

**Issue by maicss** [digitalbazaar/forge#473]
## background
I have `.pfx` file, generate by `openssl`, it works fine. 
What I need is transfer this file on the Internet. 

What I decide to do is:

> base64 this file, and tell server file's type.(I have other file, like JKS)

## problems
1, get key by using `forge.pki.oids.keyBag`

```
const forge = require('node-forge');
const fs = require('fs');

let pfxFile = fs.readFileSync('/Users/maic/Documents/ssl/client.pfx');
// convert to base64 is mock what I got from other website.
let p12b64 = Buffer(pfxFile).toString('base64');
let p12Der = forge.util.decode64(p12b64);
let p12Asn1 = forge.asn1.fromDer(p12Der);
let p12 = forge.pkcs12.pkcs12FromAsn1(p12Asn1, 'test');
let certBags = p12.getBags({bagType: forge.pki.oids.certBag});
// console.log('cert: ', bags[forge.pki.oids.certBag][0].cert);

console.log('================');

let keyBags = p12.getBags({bagType: '1.2.840.113549.1.12.10.1.2'});
console.log('cert bag type: ', forge.pki.oids.certBag);
console.log('key bag type: ', forge.pki.oids.keyBag);

console.log(certBags);
console.log(keyBags);

// result: 
cert bag type:  1.2.840.113549.1.12.10.1.3
key bag type:  1.2.840.113549.1.12.10.1.1
{ '1.2.840.113549.1.12.10.1.3': 
   [ { type: '1.2.840.113549.1.12.10.1.3',
       attributes: [Object],
       cert: [Object] } ] }
{ '1.2.840.113549.1.12.10.1.2': 
   [ { type: '1.2.840.113549.1.12.10.1.2',
       attributes: [Object],
       key: [Object] } ] }
```
I debug into `pkcs12.js` file and I get `1.2.840.113549.1.12.10.1.2`, but use `forge.pki.oids.keyBag` get `1.2.840.113549.1.12.10.1.1`

2, generate a p12 file

```
const forge = require('node-forge');
const fs = require('fs');

let clientKey = fs.readFileSync('/Users/maic/Documents/ssl/client.key');
let clientCert = fs.readFileSync('/Users/maic/Documents/ssl/client.crt');
// let p12Asn1 = forge.pkcs12.toPkcs12Asn1(clientKey, clientCert, 'test', {algorithm: '3des'});
var p12Asn1 = forge.pkcs12.toPkcs12Asn1(clientKey, clientCert, 'test');

// both methods result:

/Users/maic/Documents/code/js/Blog/node_modules/node-forge/js/asn1.js:833
  throw error;
  ^

Error: Integer too large; max is 32-bits.
    at Object.asn1.integerToDer (/Users/maic/Documents/code/js/Blog/node_modules/node-forge/js/asn1.js:831:15)
    at Object.pki.getTBSCertificate (/Users/maic/Documents/code/js/Blog/node_modules/node-forge/js/x509.js:2482:14)
    at Object.pki.certificateToAsn1 (/Users/maic/Documents/code/js/Blog/node_modules/node-forge/js/x509.js:2589:51)
    at Object.p12.toPkcs12Asn1 (/Users/maic/Documents/code/js/Blog/node_modules/node-forge/js/pkcs12.js:816:34)
    at Object.<anonymous> (/Users/maic/Documents/code/js/Blog/test-server.js:6:28)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
## questions

1, There any some better way to transfer certificate?
2, Are all above bugs  or I tried the wrong ways?

Thanks!

**Comment by giansalex** [comment]
For key, use `forge.pki.oids.pkcs8ShroudedKeyBag` = **1.2.840.113549.1.12.10.1.2**
https://github.com/digitalbazaar/forge/blob/f070f4afc37d2b0f3191ccb066e1b42c4eb3f473/tests/nodejs-create-pkcs12.js#L115
