### ISSUE TITLE
bag.cert is null

### ISSUE THREAD

**Issue by raijinsetsu** [digitalbazaar/forge#536]
I am converting an encrypted PFX to PEM.

Here is a snippet for context:
```
    const p12 = p12ToAsn1(p12str, passphrase);

    // get any key(s)
    const keyBags = [
        ...p12.getBags({ bagType: forge.pki.oids.keyBag })[forge.pki.oids.keyBag],
        ...p12.getBags({ bagType: forge.pki.oids.pkcs8ShroudedKeyBag })[forge.pki.oids.pkcs8ShroudedKeyBag]
    ];
    // get any cert(s)
    const certBags = p12.getBags({ bagType: forge.pki.oids.certBag })[forge.pki.oids.certBag];
```

When I iterate through the certBags array, one of the bags' "cert" properties is null. I found nothing in the docs about this but I saw the comment about the "key" property being null if the type is not supported by Forge. So, thinking it might be the same deal, I looked at the code and found pki.certificateFromAsn1 is used when parsing PKCS#12 into Forge's structures and any exception thrown is ignored. That's how the "cert" property is assigned "null". 

So, I did this to see the exception: `forge.pki.certificateFromAsn1(bag.asn1);`
Which produced this:
```
TypeError: bytes.getSignedInt is not a function
    at Object.asn1.derToInteger (C:\Users\lcharron\DevWorkspace\server-nodejs\node_modules\node-forge\lib\asn1.js:1110:16)
    at Object.pki.certificateExtensionFromAsn1 (C:\Users\lcharron\DevWorkspace\server-nodejs\node_modules\node-forge\lib\x509.js:1540:36)
    at Object.pki.certificateExtensionsFromAsn1 (C:\Users\lcharron\DevWorkspace\server-nodejs\node_modules\node-forge\lib\x509.js:1467:21)
    at Object.pki.certificateFromAsn1 (C:\Users\lcharron\DevWorkspace\server-nodejs\node_modules\node-forge\lib\x509.js:1395:27)
    at o.certificates.certBags.map (C:\Users\lcharron\DevWorkspace\server-nodejs\source\util\Certificates.ts:223:23)
    at Array.map (native)
    at processPFX (C:\Users\lcharron\DevWorkspace\server-nodejs\source\util\Certificates.ts:220:31)
    at Object.process (C:\Users\lcharron\DevWorkspace\server-nodejs\source\util\Certificates.ts:113:21)
    at Promise.resolve.then (C:\Users\lcharron\DevWorkspace\server-nodejs\source\protocols\native_handlers\Infr-Certificate.ts:166:42)
```

The PFX file was provided by GlobalSign and does not have issues when used with Windows or OpenSSL.  I've tried to rule out everything there is to rule out on my side.

**Comment by raijinsetsu** [comment]
I did some more digging and the first two certificates extracted from the PFX have incorrect content. I ran this code to verify a hunch:
```
const Forge = require('node-forge');
const fs = require('fs');

const buf = fs.readFileSync('local\\certificate.pfx');

const tmpA = Buffer.from(Forge.util.decode64(buf.toString('base64')));

if (buf.equals(tmpA)) {
    console.log('ok');
} else {
    console.log('not ok');
}
```

I get "not ok". That's... not ok. It looks like I have to always pass the data as a string containing the base64-encoded data and then pass that through decode64. This this intended or a bug?

**Comment by dlongley** [comment]
Encoding is probably wrong here (assumes a utf-8 string):

```js
const tmpA = Buffer.from(Forge.util.decode64(buf.toString('base64')));
```

Instead, `forge.util.decode64` outputs a  binary string:

```js
const tmpA = Buffer.from(Forge.util.decode64(buf.toString('base64')), 'binary');
```

**Comment by dlongley** [comment]
Skipping the base64-encoding stuff:

```js
// buf is now a 'binary' string forge can work with
const buf = fs.readFileSync('local\\certificate.pfx', 'binary');
```

**Comment by raijinsetsu** [comment]
"buf" would be a string and not Buffer, correct? My data starts in a Buffer, so you think I could do this:
`Forge.asn1.fromDer(buf.toString('binary'))`

**Comment by raijinsetsu** [comment]
That fixed the certificate output being incorrect for the first two certificates. However, the third certificate in the file is still not decoding - same exception I initially documented.

**Comment by raijinsetsu** [comment]
I am still seeing this issue. In case it was that specific PFX, I found another certificate and I have the same issue which is I get this exception on the third certificate: "TypeError: bytes.getSignedInt is not a function".
