### ISSUE TITLE
Use forge.min.js tell me n.randomBytes is not a function

### ISSUE THREAD

**Issue by zishang520** [digitalbazaar/forge#537]
```nodejs
forge.random.getBytesSync(32);
```
TypeError: n.randomBytes is not a function
    at Object.o.seedFileSync (E:\cache\crypto.js:7:4534)
    at r (E:\cache\crypto.js:7:2210)
    at Object.o.generateSync (E:\cache\crypto.js:7:4259)
    at Object.o.generate (E:\cache\crypto.js:7:3898)
    at Object.e.getBytesSync (E:\cache\crypto.js:1:25919)
    at Object.<anonymous> (E:\cache\index.js:18:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

**Comment by davidlehn** [comment]
What version of Node.js is this?  Or is this some other environment?  The code in `lib/prng.js` sets `_crypto` to `require('crypto')` and later calls `randomBytes()` on that, so it should work with the standard API.

**Comment by zishang520** [comment]
Thank you for your guidance, I read the source code, know where the problem lies, and my operating environment is WeChat small program, no window.crypto or window.msCrypto

**Comment by engpakravan** [comment]
i fixed up this problem in this pull request
https://github.com/digitalbazaar/forge/pull/1007
