### ISSUE TITLE
AES-ECB decryption error - tmp.length is not a function

### ISSUE THREAD

**Issue by nathanschwarz** [digitalbazaar/forge#552]
Hi,
I'm trying to use the AES_ECB decryption mentionned in the doc.
the key is a string in a file and the encrypted data is also in an other file.
These were generated with openSsl.

forge keep throwing the same error which is 
`TypeError: tmp.length is not a function
    at forge.aes.Algorithm.initialize (path_to_app/node_modules/node-forge/lib/aes.js:203:19)
    at new forge.cipher.BlockCipher (path_to_app/node_modules/node-forge/lib/cipher.js:118:18)
    at Object.forge.cipher.createDecipher (path_to_app/node_modules/node-forge/lib/cipher.js:75:10)
at Object.<anonymous> (path_to_app/main.js:179:29)
`
and there's the code
`const forge = require('node-forge')
let aes_key = fs.readFileSync(AES_KEY_PATH, 'utf8')
let encrypted = fs.readFileSync('test/a.encrypted.jpg', 'utf8')
let decipher = forge.cipher.createDecipher('AES-ECB', aes_key)
decipher.mode.unpad = false;
decipher.start(); //line 179, where the error is thrown
decipher.update(forge.util.createBuffer(encrypted));
decipher.finish();
let decrypted = decipher.output.getBytes();
fs.writeFileSync('test/a.decrypted.jpg', decrypted)
`
Could you tell me what i'm doing wrong ? Thanks

**Comment by ve3** [comment]
also happen with AES-CBC.

```
function decryptOpenssl(string, key) {
    string = window.atob(string);

    var md = forge.md.sha256.create();
    md.update(key);
    var hashKey = md.digest().toHex();
    var iv = hashKey.substr(0, 16);
    console.log(iv);

    // start error below.
    var decipher = forge.cipher.createDecipher('AES-CBC', key);
    decipher.start({'iv': iv});
    decipher.update(string);
    var result = decipher.finish();
    console.log(result);
    console.log(decipher.output.toHex());
}

decryptOpenssl('MDVlcDBvekhLYnlockJ4UTBkRm45YTlKQ2xNT1ZEL2NKbzV1czJCS0F3MD0=', 'sec_7Lk6$wMtzMbNoK%d&TgmCc5wh2oTq^');
```

should return `M66RA-GF0R2-A86WW-WF8Y3-PGW2W` but error `t.length`

**Comment by davidlehn** [comment]
@ve3: Your key length needs to be 16, 24, or 32 bytes but is 34 bytes.  Is that "sec_" prefix random or part of some other encoding?

@nathanschwarz Perhaps your key length has an issue too?  Is it really 256bits?

The forge code is handling this type of error poorly, sorry about that.  Hopefully it will be addressed in an future version.

**Comment by ve3** [comment]
sec_ prefix is static secret key I use with my OAuth application.

I have no idea about this but is it standard between programming languages that AES-256 should be 32 bytes key size, 16 for AES-128, and so on.
I found nowhere in [Wikipedia](https://en.wikipedia.org/wiki/Advanced_Encryption_Standard) or maybe I just seen it but don't understand. Because I'm trying to create encryption/decryption messages between programming languages.

**Comment by davidlehn** [comment]
Perhaps the encryption part is using pbkdf2 or similar to get a key from a passphrase and salt?  Forge does have some pbkdf2 support if that is the case.  You'd have to know what the encryption part is doing and do the same thing during decryption.  IIRC, the actual key should be one of those multiple of 8 byte lengths.
