### ISSUE TITLE
Doubts about verifying certs

### ISSUE THREAD

**Issue by vicvarros** [digitalbazaar/forge#593]
I have the next function for creating certificates:

```js
var fs = require('fs');
var { pki } = require('node-forge');

module.exports.createCertificate = function(certName, parentCertName = null) {
  if (parentCertName) {
    var parentCertPem = fs.readFileSync(`./certs/${parentCertName}.pem`);
    var parentCert = pki.certificateFromPem(parentCertPem);
  }

  var keys = pki.rsa.generateKeyPair(2048);
  var cert = pki.createCertificate();

  cert.publicKey = keys.publicKey;
  cert.serialNumber = '01';
  cert.validity.notBefore = new Date();
  cert.validity.notAfter = new Date();
  cert.validity.notAfter.setFullYear(cert.validity.notBefore.getFullYear() + 1);

  var attrs = [
    {
      name: 'commonName',
      value: certName,
    },
  ];

  var issuerAttrs = parentCertName ? parentCert.subject.attributes : attrs;

  cert.setSubject(attrs);
  cert.setIssuer(issuerAttrs);
  cert.setExtensions([
    {
      name: 'basicConstraints',
      cA: true,
    },
    {
      name: 'keyUsage',
      keyCertSign: true,
      digitalSignature: true,
      nonRepudiation: true,
      keyEncipherment: true,
      dataEncipherment: true,
    },
    {
      name: 'extKeyUsage',
      serverAuth: true,
      clientAuth: true,
      codeSigning: true,
      emailProtection: true,
      timeStamping: true,
    },
    {
      name: 'nsCertType',
      client: true,
      server: true,
      email: true,
      objsign: true,
      sslCA: true,
      emailCA: true,
      objCA: true,
    },
    {
      name: 'subjectKeyIdentifier',
    },
  ]);

  cert.sign(keys.privateKey);

  fs.writeFileSync(`./certs/${certName}.pem`, pki.certificateToPem(cert));
};
```
So, I create two certificates by running this script:

```js
var X509 = require('./X.509');

var generateCerts = async function() {
  await X509.createCertificate('RootCert');
  await X509.createCertificate('ChildCert', 'RootCert');
};

generateCerts();
```

But, when I try to verify 'ChildCert' against 'RootCert' with the next code:

```js
// certPem is 'ChildCert' in PEM format
cert = pki.certificateFromPem(certPem);

// rootCertPem is 'RootCert' in PEM format
rootCert = pki.certificateFromPem(rootCertPem);

rootCert.verify(cert);
```

I have the next error:

```
Error: Encryption block is invalid.
at _decodePkcs1_v1_5 (/usr/src/app/node_modules/node-forge/lib/rsa.js:1512:11)
at Object.verify (/usr/src/app/node_modules/node-forge/lib/rsa.js:1058:16)
at Object.key.verify (/usr/src/app/node_modules/node-forge/lib/rsa.js:1077:20)
at Object.cert.verify (/usr/src/app/node_modules/node-forge/lib/x509.js:1157:29)
at /usr/src/app/app.js:60:18
at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
at /usr/src/app/node_modules/express/lib/router/index.js:284:7
at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
```

What am I doing wrong? Could you help me please?

**Comment by vicvarros** [comment]
Solved!

I forgot to sign child cert with parent's private key.
