### ISSUE TITLE
subject alt name with ip address

### ISSUE THREAD

**Issue by ctcpip** [digitalbazaar/forge#714]
I'm trying to include an alt name with IP address, which must be an octet string per [the rfc](https://tools.ietf.org/html/rfc5280#section-4.2.1.6)

However, I always get this error:

```
Cannot use 'in' operator to search for 'bitStringContents' in 93
    at Object.asn1.toDer (asn1.js:648:1)
    at Object.asn1.toDer (asn1.js:671:1)
    at Object.asn1.toDer (asn1.js:671:1)
    at Object.pki.certificateExtensionToAsn1 (x509.js:2698:1)
    at _fillMissingFields (x509.js:2068:1)
    at Object.csr.setAttributes (x509.js:1803:1)
```

```js
  csr.setAttributes([
    {
      name: 'extensionRequest',
      extensions: [
        {
          name: 'subjectAltName',
          altNames: [
            {
              type: 2, // 2 is DNS type
              value: hostname
            },
            {
              type: 7, // 7 is IP address type
              value: ipBytes
            },
```

**Comment by davidlehn** [comment]
I think you need to use `ip: ipBytes` instead of `value:`.  That's a bit confusing.  I don't recall why the API is like that.

**Comment by ctcpip** [comment]
thanks, that was it... and I didn't need to do any conversion to bytes myself -- it expects a string literal - i.e. `'127.0.0.1'`
