### ISSUE TITLE
window is not defined error 

### ISSUE THREAD

**Issue by Zoey-rahimi** [digitalbazaar/forge#717]
I installed forge in a NativeScript project. there was not any issue in installation, but when I add 
`var forge = require("node-forge");` in the home-page.js file , I get this error.
Here is the stack trace:
```` Webpack compilation complete. Watching for file changes.
Webpack build done!
Successfully transferred bundle.651345b9e00673263e5e.hot-update.js on device emulator-5554.
Successfully transferred vendor.651345b9e00673263e5e.hot-update.js on device emulator-5554.
Successfully transferred 651345b9e00673263e5e.hot-update.json on device emulator-5554.
JS: HMR: Checking for updates to the bundle with hmr hash 651345b9e00673263e5e.
Refreshing application on device emulator-5554...
JS: HMR: Ignored an error while updating module ./home/home-page.js <self-accept-errored>
JS: HMR: ReferenceError: window is not defined
JS: HMR: Cannot apply update with hmr hash 651345b9e00673263e5e.
JS: HMR: window is not defined
Successfully transferred bundle.js on device emulator-5554.
Successfully transferred runtime.js on device emulator-5554.
Successfully transferred vendor.js on device emulator-5554.
Restarting application on device emulator-5554...
Successfully synced application org.nativescript.HelloGamma on device emulator-5554.
JS: HMR: Hot Module Replacement Enabled. Waiting for signal.
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{org.nativescript.HelloGamma/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Building UI from XML. @app-root.xml:1:1
System.err:  > window is not defined
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.HelloGamma/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Building UI from XML. @app-root.xml:1:1
System.err:  > window is not defined
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
System.err:     at android.app.ActivityThread.-wrap11(Unknown Source:0)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Building UI from XML. @app-root.xml:1:1
System.err:  > window is not defined
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1083)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1063)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1055)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:19)
System.err:     at android.app.Activity.performCreate(Activity.java:7009)
System.err:     at android.app.Activity.performCreate(Activity.java:7000)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
System.err:     ... 9 more ````

**Comment by davidlehn** [comment]
I thought all the `window` accesses had conditionals around them where needed.  Doesn't look like that stack trace says anything about where in forge the issue is?  You'll have to track the issue down.  There are only a handful of places where `window` is used.
