### ISSUE TITLE
RSAES-PKCS1-V1_5 generating a block > 256 bytes

### ISSUE THREAD

**Issue by aurbano** [digitalbazaar/forge#805]
Sorry if this is not the correct place to ask but I'm not sure if I'm using the library wrong or what's happening.

I'm using this library to generate a JWE sending an encrypted AES key, with no cipher text (the backend wants an AES key, encrypted with their public key)

Their RSA Public key comes from the backend in the format `MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA...` which I'm then importing like this:

```ts
const serverKeyPem = `-----BEGIN PUBLIC KEY-----\n${pubKeyResponse}\n-----END PUBLIC KEY-----`;
const serverKey = forge.pki.publicKeyFromPem(serverKeyPem);
```

There might be a better way but this seems to work (please let me know if there's a better way though!)

Now I generate an AES key with 32 random bytes, which will be used to encrypt using `AES256-GCM` later on.

```ts
const aesKey = forge.random.getBytesSync(32);
const encryptedAesKey = serverKey.encrypt(aesKey, 'RSAES-PKCS1-V1_5');
const encodedAesKey = base64url(encryptedAesKey);
```

Where `base64url` is a method off of stackoverflow:

```ts
function escape(str: string) {
  return str.replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '');
}

function base64url(str: string, encoding?: string) {
  return escape(Buffer.from(str, encoding || 'utf8').toString('base64'));
}
```

My issue is that the Java backend keeps throwing this error when decrypting:

```
Invalid Key received javax.crypto.IllegalBlockSizeException: Data must not be longer than 256 bytes
	at java.base/com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:347)
	at java.base/com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:392)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2208)
```

This backend is known to work as it's being used from other clients (iOS/Android), but for some reason it keeps rejecting my requests.

Any idea off the top of your head? I can provide any other information needed - I wanted to use `SubtleCrypto` but it doesn't seem to support `RSAES-PKCS1-V1_5`, only `RSA-OAEP` which the backend doesn't support at the moment.

In case you want to see it, I assemble the JWE simply by concatenating the parts:

```ts
const header = JSON.stringify({ alg: 'RSA1_5', enc: 'A256GCM' });
const jwe = [base64url(header), encodedAesKey, base64url(iv), '', ''].join('.');
```

Thanks!

**Comment by aurbano** [comment]
Turns out the main issue was the encoding of the input to `encrypt`

I haven't looked at the source but it expects the bytes to be encrypted in UTF-8, so I had to call

```ts
const encodedAesKey = forge.util.encodeUtf8(aesKey);
// and then encrypt as before
const encryptedAesKey = serverKey.encrypt(encodedAesKey, 'RSAES-PKCS1-V1_5');
```

This fixed the issue of the data being longer than 256 when trying to decrypt in Java.
