### ISSUE TITLE
PKCS7 multiple recipients issue

### ISSUE THREAD

**Issue by nas-t** [digitalbazaar/forge#928]
Hello digitalbazaar team,

when trying to exchange an RSA encrypted PKCS7 message with two recipients, I am experiencing an issue when the second recipient is trying to decrypt the message. 

## Versions installed via NPM
- @types/node-forge v0.10.9
- node-forge v0.10.0

## TS snippet reproducing the issue
```
import { pki, pkcs7, random, util} from 'node-forge';

export interface Key_t {
    privPEM: string;
    certPEM: string;
}


function generateKeyPair(): Key_t {

    const keypair = pki.rsa.generateKeyPair({bits: 2048, e: 0x10001});

    const cert = pki.createCertificate();
    cert.publicKey = keypair.publicKey;
    cert.serialNumber = '01';
    cert.validity.notBefore = new Date();
    cert.validity.notAfter = new Date();
    cert.validity.notAfter.setFullYear(cert.validity.notBefore.getFullYear() + 1);
    cert.sign(keypair.privateKey);

    return {privPEM: pki.privateKeyToPem(keypair.privateKey), certPEM: pki.certificateToPem(cert)};
  }

  function initMessage(messageText: string): pkcs7.PkcsEnvelopedData {

    const msg = pkcs7.createEnvelopedData();

    msg.content = util.createBuffer();
    msg.content.putString(messageText);

    return msg;
  }

  function addCert(msg: pkcs7.PkcsEnvelopedData, certPEM: string) {
    const cert = pki.certificateFromPem(certPEM);
    msg.addRecipient(cert);
  }


  function getMessageFromEnvelope(envelope: string, keys: Key_t): string {

    const priv = pki.decryptRsaPrivateKey(keys.privPEM);
    const p7d = pkcs7.messageFromPem(envelope) as any; // @types are missing decrypt signature
    const cert = pki.certificateFromPem(keys.certPEM);
    const recipient = p7d.findRecipient(cert);

    p7d.decrypt(recipient, priv);

    return p7d.content.toString();
  }

  function finalizeMessage(msg: pkcs7.PkcsEnvelopedData): string {
    // Finalize
    msg.encrypt();
    return pkcs7.messageToPem(msg as any);
  }


// user 1
const keypair1 = generateKeyPair();
// user 2
const keypair2 = generateKeyPair();

const msg = initMessage("This is a test, hopefully both users will be able to decrypt.");
addCert(msg, keypair1.certPEM);
addCert(msg, keypair2.certPEM);
const pkcs7Message = finalizeMessage(msg);

console.log('Trying to decrypt using user 1 private key');
const messageUser1 = getMessageFromEnvelope(pkcs7Message, keypair1);
console.log('messageUser1:', messageUser1);

console.log('Trying to decrypt using user 2 private key');
const messageUser2 = getMessageFromEnvelope(pkcs7Message, keypair2);
console.log('messageUser2:', messageUser2);
```

I'm getting the following output when running the snippet:
```
Trying to decrypt using user 1 private key
messageUser1: This is a test, hopefully both users will be able to decrypt.
Trying to decrypt using user 2 private key
/home/xyz/test/node_modules/node-forge/lib/rsa.js:1563
    throw new Error('Encryption block is invalid.');
    ^

Error: Encryption block is invalid.
    at Object._decodePkcs1_v1_5 [as decode] (/home/xyz/test/node_modules/node-forge/lib/rsa.js:1563:11)
    at Object.key.decrypt (/home/xyz/test/node_modules/node-forge/lib/rsa.js:1200:19)
    at Object.decrypt (/home/xyz/test/node_modules/node-forge/lib/pkcs7.js:681:31)
    at getMessageFromEnvelope (/home/xyz/test/dist/out-tsc/tools/test.js:30:9)
    at Object.<anonymous> (/home/xyz/test/dist/out-tsc/tools/test.js:50:20)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
```
At this point I am not sure if there is an issue within my code or if there is an issue handling multiple recipients in node-forge.

Kind Regards

**Comment by nas-t** [comment]
Found the issue within my code which was causing false positives in pkcs7.finRecipient (https://github.com/digitalbazaar/forge/blob/e1a740d0be6c773af1840e0f0620994b8beeb020/lib/pkcs7.js#L637).
Recipient 1 and 2 were using the same serial and no attributes, which caused both to match with the first recipients entry. As a minimal fix, i implemented random serial numbers for the self signed certificates.
