### ISSUE TITLE
ng build fails due to URLSearchParams is not defined at Object.<anonymous> (/usr/src/app/node_modules/node-forge/lib/log.js:305:5)

### ISSUE THREAD

**Issue by sumitcodename47** [digitalbazaar/forge#942]
We are using Angular 6.3 for our UI development and suddenly today we can issues in our deployment on AWS using docker, below is the actual error.
We are using version "node-forge": "^0.10.0"
```

Step 18/29 : RUN ng build --prod  --output-hashing=none --build-optimizer false
306 | ---> Running in f7bada3f41a0
307 | URLSearchParams is not defined
308 | ReferenceError: URLSearchParams is not defined
309 | at Object.<anonymous> (/usr/src/app/node_modules/node-forge/lib/log.js:305:5)
310 | at Module._compile (module.js:643:30)
311 | at Object.Module._extensions..js (module.js:654:10)
312 | at Module.load (module.js:556:32)
313 | at tryModuleLoad (module.js:499:12)
314 | at Function.Module._load (module.js:491:3)
315 | at Module.require (module.js:587:17)
316 | at require (internal/module.js:11:18)
317 | at Object.<anonymous> (/usr/src/app/node_modules/node-forge/lib/index.js:17:1)
318 | at Module._compile (module.js:643:30)
319 | The command '/bin/sh -c ng build --prod  --output-hashing=none --build-optimizer false' returned a non-zero code: 1
320

```
Can someone tell why this is happening suddenly?

**Comment by LiangNex** [comment]
Same here.

**Comment by LiangNex** [comment]
> 

We get this error on v1 version, which was released 6 days ago. Reverting it to `0.10.0` solves the problem.

**Comment by sumitcodename47** [comment]
yes.. I copied package-lock.json in our docker build that had 0.10.0 version and that resolved the issue.
@LiangNex you are right, the issue is with latest version.

**Comment by sumitcodename47** [comment]
@davidlehn yes, we are using Angular 6.3 and suddenly it was giving build error during docker deployment.
