### ISSUE TITLE
Cannot create pkcs7 from PEM message

### ISSUE THREAD

**Issue by titivuk** [digitalbazaar/forge#984]
Hello, I have encrypted message string that I need to decrypt.
I am trying the following
```javascript
const forge = require("node-forge");
const fs = require("fs");

const pem = fs.readFileSync("encrypted.pem");
const p7 = forge.pkcs7.messageFromPem(pem);
```
But getting the error below
```
D:\Programming\Certificate\node_modules\node-forge\lib\pkcs7.js:831
    throw error;
    ^
14)
    at Object.fromAsn1 (D:\Programming\Certificate\node_modules\←[4mnode-forge←[24m\lib\pkcs7.js:604:24)
    at Object.p7.messageFromAsn1 (D:\Programming\Certificate\node_modules\←[4mnode-forge←[24m\lib\pkcs7.js:118:7)
    at Object.p7.messageFromPem (D:\Programming\Certificate\node_modules\←[4mnode-forge←[24m\lib\pkcs7.js:59:13)
    at Object.<anonymous> (D:\Programming\Certificate\node-forge.js:5:24)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1101:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:981:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m {
  errors: [
    ←[32m'[RecipientInfo.issuerAndSerial] Expected tag class "0", got "128"'←[39m,
    ←[32m'[RecipientInfo.issuerAndSerial] Expected type "16", got "0"'←[39m,
    ←[32m'[RecipientInfo] Tag class "0", type "16" expected value length "4", got "4"'←[39m
  ]
}
```

`encrypted.pem` file contains data in format
```
-----BEGIN PKCS7-----
content
-----END PKCS7-----
```

`openssl pkcs7 -in encrypted_message_file -text` produces
```
unable to load PKCS7 object
2496:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:../openssl-1.1.1e/crypto/asn1/tasn_dec.c:1130:
2496:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:../openssl-1.1.1e/crypto/asn1/tasn_dec.c:290:Type=PKCS7_ISSUER_AND_SERIAL
2496:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:../openssl-1.1.1e/crypto/asn1/tasn_dec.c:627:Field=issuer_and_serial, Type=PKCS7_RECIP_INFO
2496:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:../openssl-1.1.1e/crypto/asn1/tasn_dec.c:595:Field=recipientinfo, Type=PKCS7_ENVELOPE
2496:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:../openssl-1.1.1e/crypto/asn1/tasn_dec.c:627:       
2496:error:0D08403A:asn1 encoding routines:asn1_template_ex_d2i:nested asn1 error:../openssl-1.1.1e/crypto/asn1/tasn_dec.c:477:Field=d.enveloped, Type=PKCS7
2496:error:0906700D:PEM routines:PEM_ASN1_read_bio:ASN1 lib:../openssl-1.1.1e/crypto/pem/pem_oth.c:33:
```

I found asn1 decoder (https://lapo.it/asn1js/) and it returns
```
SEQUENCE (2 elem)
  OBJECT IDENTIFIER 1.2.840.113549.1.7.3 envelopedData (PKCS #7)
  [0] (1 elem)
    SEQUENCE (3 elem)
      INTEGER 2
      SET (1 elem)
        SEQUENCE (4 elem)
          INTEGER 2
          [0] (20 byte) DC2C590C6581CCAB6E4104C4BFEE42E29E171019
          SEQUENCE (2 elem)
            OBJECT IDENTIFIER 1.2.840.113549.1.1.1 rsaEncryption (PKCS #1)
            NULL
          OCTET STRING (256 byte) 24C6DE67A2B02FCA140A312ECC2E3FF94BBAF0A3BABDEF5D292597C44A8FBB7F5EC47…
      SEQUENCE (3 elem)
        OBJECT IDENTIFIER 1.2.840.113549.1.7.1 data (PKCS #7)
        SEQUENCE (2 elem)
          OBJECT IDENTIFIER 1.2.840.113549.3.4 rc4 (RSADSI encryptionAlgorithm)
          NULL
        [0] (1944 byte) 51F7E4E4E027F119A395F007FFD4974DD711D8BDD6929138ACD9B64697D6FB83C55B…
```
Also openssl
```
openssl asn1parse -i -in encrypted.pem

    0:d=0  hl=4 l=2307 cons: SEQUENCE          
    4:d=1  hl=2 l=   9 prim:  OBJECT            :pkcs7-envelopedData
   15:d=1  hl=4 l=2292 cons:  cont [ 0 ]        
   19:d=2  hl=4 l=2288 cons:   SEQUENCE          
   23:d=3  hl=2 l=   1 prim:    INTEGER           :02
   26:d=3  hl=4 l= 304 cons:    SET               
   30:d=4  hl=4 l= 300 cons:     SEQUENCE          
   34:d=5  hl=2 l=   1 prim:      INTEGER           :02
   37:d=5  hl=2 l=  20 prim:      cont [ 0 ]        
   59:d=5  hl=2 l=  13 cons:      SEQUENCE          
   61:d=6  hl=2 l=   9 prim:       OBJECT            :rsaEncryption
   72:d=6  hl=2 l=   0 prim:       NULL              
   74:d=5  hl=4 l= 256 prim:      OCTET STRING      [HEX DUMP]:512_LENGTH_HEX_STRING
  334:d=3  hl=4 l=1973 cons:    SEQUENCE          
  338:d=4  hl=2 l=   9 prim:     OBJECT            :pkcs7-data
  349:d=4  hl=2 l=  12 cons:     SEQUENCE          
  351:d=5  hl=2 l=   8 prim:      OBJECT            :rc4
  361:d=5  hl=2 l=   0 prim:      NULL              
  363:d=4  hl=4 l=1944 prim:     cont [ 0 ] 
```

Could you please suggest why it fails?

**Comment by titivuk** [comment]
Issue solved. Node-forge does not soupport  1.2.840.113549.3.4 oid. I used another package to build ASN1 object from CMS data
